version: '3.1'

services:

  slave:
    image: mysql:5.7.23
    ports:
      - 3307:3306
    volumes:
      - /mysql/data/slave:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    
