version: '2'
services:
  redis:
    image: redis:3.2.9-alpine
    container_name: redis1
    ports:
      - "6379:6379"
    command: redis-server --requirepass 123456789
    volumes:
      - /mysql/redis/:/data

